name: Publish create-plugma

on:
    push:
        tags:
            - 'v*' # Triggers only on tags following a "v" versioning scheme, e.g., v1.0.0

jobs:
    publish:
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16' # Adjust based on your project’s Node.js version
                  registry-url: 'https://registry.npmjs.org'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test # Ensure tests pass before publishing

            - name: Publish to npm
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
