name: Windows Testing

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-on-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download ActiveTcl
              run: |
                  curl -LO https://downloads.activestate.com/ActiveTcl/releases/8.6.11/ActiveTcl-8.6.11.1.0000-MSWin32-x64.exe

            - name: Install ActiveTcl
              run: |
                  ./ActiveTcl-8.6.11.1.0000-MSWin32-x64.exe /quiet /norestart

            - name: Add Tcl to PATH
              run: |
                  echo "C:\Tcl\bin" >> $env:GITHUB_PATH

            - name: Run create-plugma CLI with Expect
              run: |
                  expect <<EOF
                  spawn npx create-plugma
                  expect "Select a framework:"
                  send "\r"
                  expect "Select a variant:"
                  send "\r"
                  expect "Project name:"
                  send "TestProject\r"
                  expect "Next:"
                  EOF
              shell: bash

            - name: Check if project directory was created
              run: |
                  test -d TestProject  # Confirm the project directory was created
                  test -f TestProject/package.json  # Check for package.json as an indicator of successful setup
