name: Windows Testing

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-on-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Cygwin and Expect
              run: |
                  curl -LO https://cygwin.com/setup-x86_64.exe
                  ./setup-x86_64.exe --quiet-mode --root C:\cygwin64 --local-package-dir C:\cygwin64\packages --site http://mirrors.kernel.org/sourceware/cygwin/ --packages expect

            - name: Add Cygwin to PATH
              run: |
                  echo "C:\cygwin64\bin" >> $env:GITHUB_PATH

            - name: Verify Expect Installation
              run: expect -v
              shell: bash

            - name: Run create-plugma CLI with Expect
              run: |
                  expect <<EOF
                  log_user 1
                  spawn npx create-plugma
                  interact
                  EOF
              shell: bash

            - name: Display TestProject Directory Contents
              run: |
                  echo "Contents of TestProject directory:"
                  ls TestProject
              shell: bash
