name: Run create-plugma on multiple OS

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch: # Allows manual triggering

jobs:
    test-cli:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] # Test on Ubuntu and Windows
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies for CLI
              run: |
                  cd packages/create-plugma
                  npm install

            - name: Install expect
              if: runner.os == 'Linux'
              run: sudo apt-get install -y expect

            - name: Run create-plugma CLI
              run: |
                  if [ "${{ runner.os }}" == "Windows" ]; then
                      echo "Skipping interactive CLI test on Windows"
                      exit 0
                  fi
                  expect <<EOF
                  spawn npx create-plugma@latest
                  expect "Select a framework:"
                  send "\r"
                  expect "Select a variant:"
                  send "\r"
                  expect "Project name:"
                  send "TestProject\r"
                  expect "Next:"
                  send "\r"
                  EOF

            - name: Confirm working directory after project creation
              run: |
                  echo "Current working directory:"
                  pwd
                  echo "Contents of the current directory:"
                  ls -al

            - name: Display package.json contents
              run: |
                  echo "Contents of package.json:"
                  cat package.json || echo "Failed to read package.json"
              working-directory: TestProject

            - name: Install project dependencies
              run: |
                  npm install
              working-directory: TestProject

            - name: Build the project
              run: |
                  npm run build
              working-directory: TestProject

            - name: Verify Build
              run: |
                  test -f dist/main.js && echo "Build succeeded" || (echo "Build failed" && exit 1)
              working-directory: TestProject
