name: Run create-plugma on multiple OS

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch: # Allows manual triggering

jobs:
    test-cli:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] # Test on Ubuntu and Windows
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install create-plugma locally
              run: |
                  npm install create-plugma@latest

            - name: Install expect
              run: |
                  if [[ "$RUNNER_OS" == "Windows" ]]; then
                    choco install expect
                  else
                    sudo apt-get install -y expect
                  fi

            - name: Simulate CLI Prompts
              run: |
                  expect <<EOF
                  spawn npx create-plugma@latest
                  expect "Select a framework:"
                  send "\r"    # Press Enter for the default framework (React)
                  expect "Select a variant:"
                  send "\r"    # Press Enter for the default variant
                  expect "Project name:"
                  send "TestProject\r"  # Type "TestProject" and press Enter
                  expect "Next:"
                  send "\r"    # Press Enter to confirm
                  expect eof
                  EOF

            - name: Run simulate-cli.js
              run: node simulate-cli.js

            - name: Verify TestProject directory
              run: |
                  if [ -d "TestProject" ]; then
                    echo "TestProject directory exists.";
                  else
                    echo "TestProject directory not found.";
                    exit 1;
                  fi

            - name: Display package.json contents
              run: |
                  echo "Contents of package.json:"
                  cat package.json || echo "Failed to read package.json"
              working-directory: TestProject

            - name: Install project dependencies
              run: |
                  npm install
              working-directory: TestProject

            - name: Build the project
              run: |
                  npm run build
              working-directory: TestProject

            - name: Verify Build
              run: |
                  test -f dist/main.js && echo "Build succeeded" || (echo "Build failed" && exit 1)
              working-directory: TestProject
