name: Windows Testing

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-on-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Fix Get-BinRoot for Chocolatey
              run: |
                  Set-Content -Path "C:\ProgramData\chocolatey\helpers\Get-BinRoot.ps1" -Value @'
                  function Get-BinRoot {
                      return "$env:SystemDrive\tools"
                  }
                  '@
              shell: pwsh

            - name: Install Tcl
              run: choco install activetcl -y
              shell: pwsh

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm test
