name: Run create-plugma on multiple OS

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch: # Allows manual triggering

jobs:
    test-cli:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] # Test on Ubuntu and Windows
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies for CLI
              run: |
                  cd packages/create-plugma
                  npm install

            - name: Simulate CLI prompts
              run: |
                  echo "Running create-plugma CLI..."
                  node <<EOF
                  const { spawn } = require('child_process');
                  const isWindows = process.platform === 'win32';
                  const cliCommand = isWindows ? 'npx.cmd' : 'npx';

                  const child = spawn(cliCommand, ['create-plugma@latest'], { stdio: 'pipe' });

                  child.stdout.on('data', (data) => {
                      const output = data.toString();
                      console.log(output);

                      if (output.includes('Select a framework:')) child.stdin.write('\n'); // Press Enter
                      if (output.includes('Select a variant:')) child.stdin.write('\n');   // Press Enter
                      if (output.includes('Project name:')) child.stdin.write('TestProject\n');
                      if (output.includes('Next:')) child.stdin.write('\n');             // Press Enter
                  });

                  child.stderr.on('data', (data) => {
                      console.error(data.toString());
                  });

                  child.on('close', (code) => {
                      if (code !== 0) {
                          console.error('CLI process exited with code:', code);
                          process.exit(code);
                      } else {
                          console.log('CLI process completed successfully.');
                      }
                  });
                  EOF

            - name: Confirm working directory after project creation
              run: |
                  echo "Current working directory:"
                  pwd
                  echo "Contents of the current directory:"
                  ls -al
              shell: bash

            - name: Display package.json contents
              run: |
                  echo "Contents of package.json:"
                  cat package.json || echo "Failed to read package.json"
              working-directory: TestProject

            - name: Install project dependencies
              run: |
                  npm install
              working-directory: TestProject

            - name: Build the project
              run: |
                  npm run build
              working-directory: TestProject

            - name: Verify Build
              run: |
                  test -f dist/main.js && echo "Build succeeded" || (echo "Build failed" && exit 1)
              working-directory: TestProject
