name: Run create-plugma on multiple OS

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch: # Allows manual triggering

jobs:
    test-cli:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] # Test on Ubuntu and Windows
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install create-plugma locally
              run: |
                  npm install create-plugma@latest

            - name: Install execa
              run: npm install execa

            - name: Write simulate-cli.js
              run: |
                  printf "(async () => {\n" > simulate-cli.js
                  printf "  try {\n" >> simulate-cli.js
                  printf "    const { execa } = await import('execa');\n" >> simulate-cli.js
                  printf "    const cli = execa('npx', ['create-plugma@latest'], { stdin: 'pipe', stdout: process.stdout, stderr: process.stderr });\n" >> simulate-cli.js
                  printf "    const inputResponses = ['\\\\n', '\\\\n', 'TestProject\\\\n', '\\\\n'];\n" >> simulate-cli.js
                  printf "    console.log('Starting CLI prompts...');\n" >> simulate-cli.js
                  printf "    for (const response of inputResponses) {\n" >> simulate-cli.js
                  printf "      console.log(\`Sending response: \${response.trim() || '<Enter>'}\`);\n" >> simulate-cli.js
                  printf "      await new Promise((resolve) => setTimeout(resolve, 500));\n" >> simulate-cli.js
                  printf "      cli.stdin.write(response);\n" >> simulate-cli.js
                  printf "    }\n" >> simulate-cli.js
                  printf "    cli.stdin.end();\n" >> simulate-cli.js
                  printf "    const { stdout } = await cli;\n" >> simulate-cli.js
                  printf "    console.log('CLI completed successfully:', stdout);\n" >> simulate-cli.js
                  printf "  } catch (error) {\n" >> simulate-cli.js
                  printf "    console.error('Error running create-plugma CLI:', error);\n" >> simulate-cli.js
                  printf "    process.exit(1);\n" >> simulate-cli.js
                  printf "  }\n" >> simulate-cli.js
                  printf "})();\n" >> simulate-cli.js

            - name: Run simulate-cli.js
              run: node simulate-cli.js

            - name: Verify TestProject directory
              run: |
                  if [ -d "TestProject" ]; then
                    echo "TestProject directory exists.";
                  else
                    echo "TestProject directory not found.";
                    exit 1;
                  fi

            - name: Display package.json contents
              run: |
                  echo "Contents of package.json:"
                  cat package.json || echo "Failed to read package.json"
              working-directory: TestProject

            - name: Install project dependencies
              run: |
                  npm install
              working-directory: TestProject

            - name: Build the project
              run: |
                  npm run build
              working-directory: TestProject

            - name: Verify Build
              run: |
                  test -f dist/main.js && echo "Build succeeded" || (echo "Build failed" && exit 1)
              working-directory: TestProject
