name: Run create-plugma on multiple OS

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch: # Allows manual triggering

jobs:
    test-cli:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] # Test on Ubuntu and Windows
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies for CLI
              run: |
                  cd packages/create-plugma
                  npm install

            - name: Write Node.js script for CLI prompts
              run: |
                  echo "const { spawn } = require('child_process');" > simulate-cli.js
                  echo "const isWindows = process.platform === 'win32';" >> simulate-cli.js
                  echo "const cliCommand = isWindows ? 'npx.cmd' : 'npx';" >> simulate-cli.js
                  echo "const child = spawn(cliCommand, ['create-plugma@latest'], { stdio: 'pipe' });" >> simulate-cli.js
                  echo "child.stdout.on('data', (data) => {" >> simulate-cli.js
                  echo "  const output = data.toString();" >> simulate-cli.js
                  echo "  console.log(output);" >> simulate-cli.js
                  echo "  if (output.includes('Select a framework:')) child.stdin.write('\\n');" >> simulate-cli.js
                  echo "  if (output.includes('Select a variant:')) child.stdin.write('\\n');" >> simulate-cli.js
                  echo "  if (output.includes('Project name:')) child.stdin.write('TestProject\\n');" >> simulate-cli.js
                  echo "  if (output.includes('Next:')) child.stdin.write('\\n');" >> simulate-cli.js
                  echo "});" >> simulate-cli.js
                  echo "child.stderr.on('data', (data) => {" >> simulate-cli.js
                  echo "  console.error(data.toString());" >> simulate-cli.js
                  echo "});" >> simulate-cli.js
                  echo "child.on('close', (code) => {" >> simulate-cli.js
                  echo "  if (code !== 0) {" >> simulate-cli.js
                  echo "    console.error('CLI process exited with code:', code);" >> simulate-cli.js
                  echo "    process.exit(code);" >> simulate-cli.js
                  echo "  } else {" >> simulate-cli.js
                  echo "    console.log('CLI process completed successfully.');" >> simulate-cli.js
                  echo "  }" >> simulate-cli.js
                  echo "});" >> simulate-cli.js

            - name: Simulate CLI prompts
              run: |
                  node simulate-cli.js

            - name: Confirm working directory after project creation
              run: |
                  echo "Current working directory:"
                  pwd
                  echo "Contents of the current directory:"
                  ls -al

            - name: Display package.json contents
              run: |
                  echo "Contents of package.json:"
                  cat package.json || echo "Failed to read package.json"
              working-directory: TestProject

            - name: Install project dependencies
              run: |
                  npm install
              working-directory: TestProject

            - name: Build the project
              run: |
                  npm run build
              working-directory: TestProject

            - name: Verify Build
              run: |
                  test -f dist/main.js && echo "Build succeeded" || (echo "Build failed" && exit 1)
              working-directory: TestProject
