name: Run create-plugma on multiple OS

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch: # Allows manual triggering

jobs:
    test-cli:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest] # Test on Ubuntu and Windows
        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install dependencies for CLI
              run: |
                  cd packages/create-plugma
                  npm install

            - name: Simulate CLI prompts
              run: |
                  node -e "
                  const { spawn } = require('child_process');
                  const child = spawn('npx', ['create-plugma@latest'], { stdio: 'pipe' });

                  child.stdout.on('data', (data) => {
                      const output = data.toString();
                      console.log(output);

                      if (output.includes('Select a framework:')) child.stdin.write('\n');
                      if (output.includes('Select a variant:')) child.stdin.write('\n');
                      if (output.includes('Project name:')) child.stdin.write('TestProject\n');
                      if (output.includes('Next:')) child.stdin.write('\n');
                  });

                  child.on('close', (code) => {
                      process.exit(code);
                  });
                  "
              shell: node

            - name: Confirm working directory after project creation
              run: |
                  echo "Current working directory:"
                  pwd
                  echo "Contents of the current directory:"
                  ls -al
              shell: bash

            - name: Display package.json contents
              run: |
                  echo "Contents of package.json:"
                  cat package.json || echo "Failed to read package.json"
              working-directory: TestProject

            - name: Install project dependencies
              run: |
                  npm install
              working-directory: TestProject

            - name: Build the project
              run: |
                  npm run build
              working-directory: TestProject

            - name: Verify Build
              run: |
                  test -f dist/main.js && echo "Build succeeded" || (echo "Build failed" && exit 1)
              working-directory: TestProject
