name: Windows Testing

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-on-windows:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Cygwin and Expect
              run: |
                  curl -LO https://cygwin.com/setup-x86_64.exe
                  ./setup-x86_64.exe --quiet-mode --packages expect

            - name: Add Cygwin to PATH
              run: |
                  echo "C:\cygwin64\bin" >> $env:GITHUB_PATH

            - name: Verify Expect Installation
              run: expect -v
              shell: bash

            - name: Run create-plugma CLI with Expect
              run: |
                  expect <<EOF
                  spawn npx create-plugma
                  expect "Select a framework:"
                  send "\r"
                  expect "Select a variant:"
                  send "\r"
                  expect "Project name:"
                  send "TestProject\r"
                  expect "Next:"
                  EOF
              shell: bash

            - name: Check if project directory was created
              run: |
                  test -d TestProject  # Confirm the project directory was created
                  test -f TestProject/package.json  # Check for package.json as an indicator of successful setup
